{
 "title": "Fitness dashboard",
 "time": { "from": "2016-04-09T22:54:11.692Z", "to": "2016-05-12T11:40:17.115Z" },
 "panels": [
  {
   "title": "Calories per day for each user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  activity_date AS \"time\",\n  user_id AS metric,\n  calories\nFROM daily_activity\nWHERE\n  $__timeFilter(activity_date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Total steps per day for each user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  activity_date AS \"time\",\n  user_id AS metric,\n  total_steps AS \"total_distance\"\nFROM daily_activity\nWHERE\n  $__timeFilter(activity_date)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Distance per day for each user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  activity_date AS \"time\",\n  user_id AS metric,\n  total_distance\nFROM daily_activity\nWHERE\n  $__timeFilter(activity_date)\nORDER BY 1,2"
    }
   ]
  }
 ]
}